### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by russelljjarvis** [openworm/tests#7]
I have added these lines to a Dockerfile
https://github.com/russelljjarvis/tests/blob/master/Dockerfile#L28-L37
``` docker
WORKDIR $HOME/wormtests
COPY . $HOME/wormtests
ENV OPENWORM_HOME .
RUN echo $OPENWORM_HOME
RUN sudo /opt/conda/bin/pip install quantities
# Comment out clones when done 
RUN git clone https://github.com/openworm/ChannelWorm.git
RUN git clone https://github.com/openworm/CElegansNeuroML.git
RUN sudo /opt/conda/bin/pip install -e . --process-dependency-links
```
It almost installs by running the last run, but it fails on quantities:
``` stracktrace
Requirement already satisfied: python-dateutil>=2 in /opt/conda/lib/python3.5/site-packages (from pandas>=0.18->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: pytz>=2011k in /opt/conda/lib/python3.5/site-packages (from pandas>=0.18->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: numpy>=1.7.0 in /opt/conda/lib/python3.5/site-packages (from pandas>=0.18->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg (from ipython->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: decorator in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: simplegeneric>0.8 in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: pygments in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: traitlets>=4.2 in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.3 in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: six>=1.10 in /opt/conda/lib/python3.5/site-packages (from matplotlib->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.5/site-packages/cycler-0.10.0-py3.5.egg (from matplotlib->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /opt/conda/lib/python3.5/site-packages (from matplotlib->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: beautifulsoup4 in /opt/conda/lib/python3.5/site-packages (from bs4->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: tornado>=4.0 in /opt/conda/lib/python3.5/site-packages (from ipykernel->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: jupyter-client in /opt/conda/lib/python3.5/site-packages (from ipykernel->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.5/site-packages (from nbformat->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: jupyter-core in /opt/conda/lib/python3.5/site-packages (from nbformat->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /opt/conda/lib/python3.5/site-packages (from nbformat->sciunit>=0.19->owtests==0.1)
Collecting gitdb2>=2.0.0 (from gitpython->sciunit>=0.19->owtests==0.1)
  Downloading gitdb2-2.0.3-py2.py3-none-any.whl (63kB)
Requirement already satisfied: h5py>=2.3.1 in /opt/conda/lib/python3.5/site-packages (from allensdk==0.14.2->neuronunit>=0.19->owtests==0.1)
Requirement already satisfied: jinja2>=2.7.3 in /opt/conda/lib/python3.5/site-packages (from allensdk==0.14.2->neuronunit>=0.19->owtests==0.1)
Requirement already satisfied: pynrrd>=0.2.1 in /opt/conda/lib/python3.5/site-packages/pynrrd-0.2.1-py3.5.egg (from allensdk==0.14.2->neuronunit>=0.19->owtests==0.1)
Requirement already satisfied: future>=0.14.3 in /opt/conda/lib/python3.5/site-packages/future-0.16.0-py3.5.egg (from allensdk==0.14.2->neuronunit>=0.19->owtests==0.1)
Requirement already satisfied: requests in /opt/conda/lib/python3.5/site-packages (from allensdk==0.14.2->neuronunit>=0.19->owtests==0.1)
Requirement already satisfied: requests-toolbelt in /opt/conda/lib/python3.5/site-packages/requests_toolbelt-0.8.0-py3.5.egg (from allensdk==0.14.2->neuronunit>=0.19->owtests==0.1)
Requirement already satisfied: simplejson>=3.10.0 in /opt/conda/lib/python3.5/site-packages (from allensdk==0.14.2->neuronunit>=0.19->owtests==0.1)
Requirement already satisfied: argparse in /opt/conda/lib/python3.5/site-packages/argparse-1.1-py3.5.egg (from pyNeuroML>-0.3.10->neuronunit>=0.19->owtests==0.1)
Collecting pylems>=0.4.9.1 (from pyNeuroML>-0.3.10->neuronunit>=0.19->owtests==0.1)
  Downloading PyLEMS-0.4.9.1.tar.gz (51kB)
Requirement already satisfied: airspeed==0.5.4dev-20150515 in /opt/conda/lib/python3.5/site-packages/airspeed-0.5.4.dev20150515-py3.5.egg (from pyNeuroML>-0.3.10->neuronunit>=0.19->owtests==0.1)
Collecting libNeuroML>=0.2.39 (from pyNeuroML>-0.3.10->neuronunit>=0.19->owtests==0.1)
  Downloading libNeuroML-0.2.39.tar.gz (194kB)
Collecting apipkg>=1.4 (from execnet->neuronunit>=0.19->owtests==0.1)
  Downloading apipkg-1.4-py2.py3-none-any.whl
Collecting backports.weakref (from backports.tempfile->neuronunit>=0.19->owtests==0.1)
  Downloading backports.weakref-1.0.post1-py2.py3-none-any.whl
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.5/site-packages (from prompt-toolkit<2.0.0,>=1.0.3->ipython->sciunit>=0.19->owtests==0.1)
Requirement already satisfied: pyzmq>=13 in /opt/conda/lib/python3.5/site-packages (from jupyter-client->ipykernel->sciunit>=0.19->owtests==0.1)
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->gitpython->sciunit>=0.19->owtests==0.1)
  Downloading smmap2-2.0.3-py2.py3-none-any.whl
Requirement already satisfied: MarkupSafe in /opt/conda/lib/python3.5/site-packages (from jinja2>=2.7.3->allensdk==0.14.2->neuronunit>=0.19->owtests==0.1)
Requirement already satisfied: cachetools==0.8.0 in /opt/conda/lib/python3.5/site-packages/cachetools-0.8.0-py3.5.egg (from airspeed==0.5.4dev-20150515->pyNeuroML>-0.3.10->neuronunit>=0.19->owtests==0.1)
Building wheels for collected packages: quantities, neo, igor, allensdk, pyNeuroML, pyNN, pylems, libNeuroML
  Running setup.py bdist_wheel for quantities: started
  Running setup.py bdist_wheel for quantities: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/88/ff/0e/34ded60ca6cddc546c9d824f41950fd972e6fdb5f5352acb80
  Running setup.py bdist_wheel for neo: started
  Running setup.py bdist_wheel for neo: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/0c/d1/7b/0dd873da92881840dda3bc6c17f1d524c1c91d61eecd7fc31c
  Running setup.py bdist_wheel for igor: started
  Running setup.py bdist_wheel for igor: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/7b/bd/03/ad854b951a448202054743cd21f08823414b0030ec9cd76eda
  Running setup.py bdist_wheel for allensdk: started
  Running setup.py bdist_wheel for allensdk: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/4c/5e/31/3c73255526e4aae0e48a02b9f3d84b197e66c42061c505fd71
  Running setup.py bdist_wheel for pyNeuroML: started
  Running setup.py bdist_wheel for pyNeuroML: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/db/9a/9f/08eca622ddadb33c9baec2a4d540706be4be19e439eff6bbc1
  Running setup.py bdist_wheel for pyNN: started
  Running setup.py bdist_wheel for pyNN: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/c5/14/8d/827d238f205e1a8f29ec6bc7ef0047c8f0444f9ad48fb15247
  Running setup.py bdist_wheel for pylems: started
  Running setup.py bdist_wheel for pylems: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/6e/a3/2b/4a086899edf741330511614b01dc46e1463e10d72cd8f3777d
  Running setup.py bdist_wheel for libNeuroML: started
  Running setup.py bdist_wheel for libNeuroML: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/08/3d/22/133d74ce8d20caec9e5a1cffa6eab09dd6f4774eb259db610d
Successfully built quantities neo igor allensdk pyNeuroML pyNN pylems libNeuroML
Installing collected packages: quantities, smmap2, gitdb2, gitpython, sciunit, neo, igor, allensdk, pylems, libNeuroML, pyNeuroML, pyNN, apipkg, execnet, backports.weakref, backports.tempfile, neuronunit, owtests
  Found existing installation: quantities 0.11.1
    Uninstalling quantities-0.11.1:
      Successfully uninstalled quantities-0.11.1
  Rolling back uninstall of quantities
Exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2603, in get_entry_map
    ep_map = self._ep_map
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2574, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/conda/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/conda/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/opt/conda/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/opt/conda/lib/python3.5/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/opt/conda/lib/python3.5/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/dist.py", line 316, in __init__
    for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 731, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2606, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2336, in parse_map
    for group, lines in data:
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2935, in split_sections
    for line in yield_lines(s):
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2202, in yield_lines
    for ss in strs:
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2531, in _get_metadata
    if self.has_metadata(name):
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.5/site-packages/quantities-0.11.1-py3.5.egg'
The command '/bin/sh -c sudo /opt/conda/bin/pip install -e . --process-dependency-links' returned a non-zero code: 2
russell@rjjarvis:~/git/wormtests$ 
```

**Comment by russelljjarvis** [comment]
Without docker and just raw BASH on Ubuntu I get:
``` bash
Installed /tmp/easy_install-l4XsIA/allensdk-0.14.2/.eggs/snowballstemmer-1.2.1-py2.7.egg
Searching for docutils>=0.11
Reading https://pypi.python.org/simple/docutils/
Best match: docutils 0.14
Downloading https://pypi.python.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz#md5=c53768d63db3873b7d452833553469de
Processing docutils-0.14.tar.gz
Writing /tmp/easy_install-l4XsIA/allensdk-0.14.2/temp/easy_install-dcHI3d/docutils-0.14/setup.cfg
Running docutils-0.14/setup.py -q bdist_egg --dist-dir /tmp/easy_install-l4XsIA/allensdk-0.14.2/temp/easy_install-dcHI3d/docutils-0.14/egg-dist-tmp-XTZa5M
warning: no files found matching 'MANIFEST'
warning: no previously-included files matching '*.pyc' found under directory '*'
warning: no previously-included files matching '*~' found under directory '*'
warning: no previously-included files matching '.DS_Store' found under directory '*'
zip_safe flag not set; analyzing archive contents...
docutils.writers.docutils_xml: module references __path__
docutils.writers.html4css1.__init__: module references __file__
docutils.writers.pep_html.__init__: module references __file__
docutils.writers.html5_polyglot.__init__: module references __file__
docutils.writers.odf_odt.__init__: module references __file__
docutils.writers.s5_html.__init__: module references __file__
docutils.writers.latex2e.__init__: module references __file__
docutils.parsers.rst.directives.misc: module references __file__
creating /tmp/easy_install-l4XsIA/allensdk-0.14.2/.eggs/docutils-0.14-py2.7.egg
Extracting docutils-0.14-py2.7.egg to /tmp/easy_install-l4XsIA/allensdk-0.14.2/.eggs

Installed /tmp/easy_install-l4XsIA/allensdk-0.14.2/.eggs/docutils-0.14-py2.7.egg
error: idna 2.0 is installed but idna<2.7,>=2.5 is required
```
Even after running:
```
 sudo pip install --upgrade idna
```

**Comment by rgerkin** [comment]
You must have old cruft in your Docker build.  For example, you shouldn't be installing quantities manually anymore (the bug that motivated it was fixed months ago).  I have no problem (at least through the first few steps with):  

```
docker run -it jupyter/scipy-notebook /bin/bash
```

and then inside the container

```
mkdir openworm
export OPENWORM_HOME=/home/jovyan/work/openworm
cd $OPENWORM_HOME
git clone http://github.com/openworm/tests; cd tests
pip install -e . --process-dependency-links
```

That at least gets you past the first part of installation.  I'll check to see if the subprojects are installing correctly now.

**Comment by russelljjarvis** [comment]
AOK, yes well it installs on raw system now. 

If I `git clone` the lastest `idna`
and then run
`sudo python3 setup.py install`, in idna and then owtests.

I have not tried opening the `musclemodel.ipynb` yet, as that would be the real test of if everything works.

I prefer to run on Docker instead of the raw system. Docker builds just give me more confidence in the standardization of the environment.

**Comment by russelljjarvis** [comment]
I have replicated this exercise, using jupyter/scipy-notebook as above.

I think I can have a much fresher Dockerfile:
``` docker
FROM jupyter/scipy-notebook
# Comment out clones when done 
RUN git clone https://github.com/openworm/ChannelWorm.git
WORKDIR ChannelWorm 
RUN sudo /opt/conda/bin/pip install -e . 
RUN git clone https://github.com/openworm/CElegansNeuroML.git
WORKDIR CElegansNeuroML 
RUN sudo /opt/conda/bin/pip install -e . 
ENV OPENWORM_HOME pwd
RUN sudo /opt/conda/bin/pip install -e . --process-dependency-links
```

**Comment by russelljjarvis** [comment]
Also things are better on raw BASH an overlooked dependancy is _tkinter',

Error:
ImportError: No named '_tkinter', please install the python3-tk package
Workaround:
```
sudo apt-get install python3-tk 

```

**Comment by rgerkin** [comment]
I'm not sure where all of these errors are coming from, but if you move to the jupyter/scipy-notebook docker container they will all go away.
